version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/sample-rails-docker
    links:
      - mysql
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
  mysql:
    image: mysql:5.7.24
    environment: # this project is sample project and development environment, so hard coding password. 
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql_data:/var/lib/mysql